algoritmo "ATIVIDADE 3"
var
   S: inteiro
   N, m: caractere
inicio
      Escreva ("Digite o nome do funcionário: ")
      Leia (N)
      Escreva("Digite o salário do funcionário: ")
      Leia (S)
      Escreva("Digite o mês a fazer o pago: ")
      Leia (m)
      Escreval("Nome do funcionário: ", N)
      Escreval("Salário: ", S)
      Escreval("O funcionário ", N, " tem um salário de ", S, " para receber em ", m)
fimalgoritmo