algoritmo "ATIVIDADE 11"
var
   a, b, c, delta: real
inicio
      Escreva("Digite o valor do coenficiente de a: ")
      Leia(a)
      Escreva("Digitie o valor do coeficiente de b: ")
      Leia(b)
      Escreva("Digite o valor do coeficiente de c: ")
      Leia(c)
      delta <- b^2 - 4*a*c
      Escreval("-------------------------")
      Escreval("   Resultado calculado   ")
      Escreval("-------------------------")
      Escreval("O valor de delta é ", delta)
fimalgoritmo